;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	count-lines-page
	downcase-region
	kill-region
	))

(setq mc/cmds-to-run-once
      '(
	end-of-buffer
	indent-for-tab-command
	))
